version: '3'
services:
  frontend:
    links:
      - backend:backend
    build: 
      context: ./frontend
    ports:
      - "8080:5000"
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
